package: simpleshop
version: '4.5.10'
author: FriendsOfREDAXO
debug_email: dev@kreatif.it
compile: 0

page:
    title: Simpleshop
    perm: shop[]
    pjax: false
    icon: rex-icon fa-shopping-cart
    subpages:
        settings:
            title: translate:settings
        variants:
            title: translate:label.variants
            hidden: true
        yform_functions:
            title: yform_functions
            hidden: true
        orders_export:
            title: translate:orders_export
            perm: shop[orders_export]
        settings_adv:
            title: translate:label.advanced_settings
            perm: shop[advanced_settings]



requires:
    redaxo: '>=5.3'
    packages:
        yform: '>=2.3,<4'
        yform/manager: '>=2.3,<4'
        sprog: '^1.0'
        kreatif: '>=4.9.0,<4.11'